config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :log_entries
  resources :crew_members
  resources :creatures
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/creature.rb
class Creature < ApplicationRecord
end

app/models/crew_member.rb
class CrewMember < ApplicationRecord
  has_many :log_entry
end

app/models/log_entry.rb
class LogEntry < ApplicationRecord
  belongs_to :crew_member
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/creatures_controller.rb
class CreaturesController < ApplicationController
  before_action :set_creature, only: %i[ show edit update destroy ]

  # GET /creatures or /creatures.json
  def index
    @creatures = Creature.all
  end

  # GET /creatures/1 or /creatures/1.json
  def show
  end

  # GET /creatures/new
  def new
    @creature = Creature.new
  end

  # GET /creatures/1/edit
  def edit
  end

  # POST /creatures or /creatures.json
  def create
    @creature = Creature.new(creature_params)

    respond_to do |format|
      if @creature.save
        format.html { redirect_to @creature, notice: "Creature was successfully created." }
        format.json { render :show, status: :created, location: @creature }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @creature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /creatures/1 or /creatures/1.json
  def update
    respond_to do |format|
      if @creature.update(creature_params)
        format.html { redirect_to @creature, notice: "Creature was successfully updated." }
        format.json { render :show, status: :ok, location: @creature }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @creature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /creatures/1 or /creatures/1.json
  def destroy
    @creature.destroy
    respond_to do |format|
      format.html { redirect_to creatures_url, notice: "Creature was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_creature
      @creature = Creature.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def creature_params
      params.require(:creature).permit(:description, :avg_height, :avg_weight, :avg_length, :t_domain, :t_kingdom, :t_phylum, :t_class, :t_order, :t_family, :t_genus, :t_species)
    end
end

app/controllers/crew_members_controller.rb
class CrewMembersController < ApplicationController
  before_action :set_crew_member, only: %i[ show edit update destroy ]

  # GET /crew_members or /crew_members.json
  def index
    @crew_members = CrewMember.all
  end

  # GET /crew_members/1 or /crew_members/1.json
  def show
  end

  # GET /crew_members/new
  def new
    @crew_member = CrewMember.new
  end

  # GET /crew_members/1/edit
  def edit
  end

  # POST /crew_members or /crew_members.json
  def create
    @crew_member = CrewMember.new(crew_member_params)

    respond_to do |format|
      if @crew_member.save
        format.html { redirect_to @crew_member, notice: "Crew member was successfully created." }
        format.json { render :show, status: :created, location: @crew_member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @crew_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /crew_members/1 or /crew_members/1.json
  def update
    respond_to do |format|
      if @crew_member.update(crew_member_params)
        format.html { redirect_to @crew_member, notice: "Crew member was successfully updated." }
        format.json { render :show, status: :ok, location: @crew_member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @crew_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /crew_members/1 or /crew_members/1.json
  def destroy
    @crew_member.destroy
    respond_to do |format|
      format.html { redirect_to crew_members_url, notice: "Crew member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_crew_member
      @crew_member = CrewMember.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def crew_member_params
      params.require(:crew_member).permit(:title, :first_name, :last_name, :job)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/log_entries_controller.rb
class LogEntriesController < ApplicationController
  before_action :set_log_entry, only: %i[ show edit update destroy ]

  # GET /log_entries or /log_entries.json
  def index
    @log_entries = LogEntry.all
  end

  # GET /log_entries/1 or /log_entries/1.json
  def show
  end

  # GET /log_entries/new
  def new
    @log_entry = LogEntry.new
  end

  # GET /log_entries/1/edit
  def edit
  end

  # POST /log_entries or /log_entries.json
  def create
    @log_entry = LogEntry.new(log_entry_params)

    respond_to do |format|
      if @log_entry.save
        format.html { redirect_to @log_entry, notice: "Log entry was successfully created." }
        format.json { render :show, status: :created, location: @log_entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @log_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /log_entries/1 or /log_entries/1.json
  def update
    respond_to do |format|
      if @log_entry.update(log_entry_params)
        format.html { redirect_to @log_entry, notice: "Log entry was successfully updated." }
        format.json { render :show, status: :ok, location: @log_entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @log_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /log_entries/1 or /log_entries/1.json
  def destroy
    @log_entry.destroy
    respond_to do |format|
      format.html { redirect_to log_entries_url, notice: "Log entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_log_entry
      @log_entry = LogEntry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def log_entry_params
      params.require(:log_entry).permit(:log_type, :day_written, :content, :crew_member_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/creatures_helper.rb
module CreaturesHelper
end

app/helpers/crew_members_helper.rb
module CrewMembersHelper
end

app/helpers/crews_helper.rb
module CrewsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/log_entries_helper.rb
module LogEntriesHelper
end

app/views/creatures/_form.html.erb
<%= form_with(model: creature, local: true) do |form| %>
  <% if creature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(creature.errors.count, "error") %> prohibited this creature from being saved:</h2>

      <ul>
      <% creature.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :avg_height %>
    <%= form.text_field :avg_height %>
  </div>

  <div class="field">
    <%= form.label :avg_weight %>
    <%= form.text_field :avg_weight %>
  </div>

  <div class="field">
    <%= form.label :avg_length %>
    <%= form.text_field :avg_length %>
  </div>

  <div class="field">
    <%= form.label 'Domain' %>
    <%= form.text_field :t_domain %>
  </div>

  <div class="field">
    <%= form.label 'Kingdom' %>
    <%= form.text_field :t_kingdom %>
  </div>

  <div class="field">
    <%= form.label 'Phylum' %>
    <%= form.text_field :t_phylum %>
  </div>

  <div class="field">
    <%= form.label 'Class' %>
    <%= form.text_field :t_class %>
  </div>

  <div class="field">
    <%= form.label 'Order' %>
    <%= form.text_field :t_order %>
  </div>

  <div class="field">
    <%= form.label 'Family' %>
    <%= form.text_field :t_family %>
  </div>

  <div class="field">
    <%= form.label 'Genus' %>
    <%= form.text_field :t_genus %>
  </div>

  <div class="field">
    <%= form.label 'Species' %>
    <%= form.text_field :t_species %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/creatures/edit.html.erb
<h1>Editing Creature</h1>

<%= render 'form', creature: @creature %>

<%= link_to 'Show', @creature %> |
<%= link_to 'Back', creatures_path %>

app/views/creatures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Creatures</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Avg height</th>
      <th>Avg weight</th>
      <th>Avg length</th>
      <th>Domain</th>
      <th>Kingdom</th>
      <th>Phylum</th>
      <th>Class</th>
      <th>Order</th>
      <th>Family</th>
      <th>Genus</th>
      <th>Species</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @creatures.each do |creature| %>
      <tr>
        <td><%= creature.description %></td>
        <td><%= creature.avg_height %></td>
        <td><%= creature.avg_weight %></td>
        <td><%= creature.avg_length %></td>
        <td><%= creature.t_domain %></td>
        <td><%= creature.t_kingdom %></td>
        <td><%= creature.t_phylum %></td>
        <td><%= creature.t_class %></td>
        <td><%= creature.t_order %></td>
        <td><%= creature.t_family %></td>
        <td><%= creature.t_genus %></td>
        <td><%= creature.t_species %></td>
        <td><%= link_to 'Show', creature %></td>
        <td><%= link_to 'Edit', edit_creature_path(creature) %></td>
        <td><%= link_to 'Destroy', creature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Creature', new_creature_path %>

app/views/creatures/new.html.erb
<h1>New Creature</h1>

<%= render 'form', creature: @creature %>

<%= link_to 'Back', creatures_path %>

app/views/creatures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @creature.description %>
</p>

<p>
  <strong>Avg height:</strong>
  <%= @creature.avg_height %>
</p>

<p>
  <strong>Avg weight:</strong>
  <%= @creature.avg_weight %>
</p>

<p>
  <strong>Avg length:</strong>
  <%= @creature.avg_length %>
</p>

<p>
  <strong>Domain:</strong>
  <%= @creature.t_domain %>
</p>

<p>
  <strong>Kingdom:</strong>
  <%= @creature.t_kingdom %>
</p>

<p>
  <strong>Phylum:</strong>
  <%= @creature.t_phylum %>
</p>

<p>
  <strong>Class:</strong>
  <%= @creature.t_class %>
</p>

<p>
  <strong>Order:</strong>
  <%= @creature.t_order %>
</p>

<p>
  <strong>Family:</strong>
  <%= @creature.t_family %>
</p>

<p>
  <strong>Genus:</strong>
  <%= @creature.t_genus %>
</p>

<p>
  <strong>Species:</strong>
  <%= @creature.t_species %>
</p>

<%= link_to 'Edit', edit_creature_path(@creature) %> |
<%= link_to 'Back', creatures_path %>

app/views/crew_members/_form.html.erb
<%= form_with(model: crew_member, local: true) do |form| %>
  <% if crew_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(crew_member.errors.count, "error") %> prohibited this crew_member from being saved:</h2>

      <ul>
      <% crew_member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :job %>
    <%= form.text_field :job %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/crew_members/edit.html.erb
<h1>Editing Crew Member</h1>

<%= render 'form', crew_member: @crew_member %>

<%= link_to 'Show', @crew_member %> |
<%= link_to 'Back', crew_members_path %>

app/views/crew_members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Crew Members</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Job</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @crew_members.each do |crew_member| %>
      <tr>
        <td><%= crew_member.id %></td>
        <td><%= crew_member.title %></td>
        <td><%= crew_member.first_name %></td>
        <td><%= crew_member.last_name %></td>
        <td><%= crew_member.job %></td>
        <td><%= link_to 'Show', crew_member %></td>
        <td><%= link_to 'Edit', edit_crew_member_path(crew_member) %></td>
        <td><%= link_to 'Destroy', crew_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Crew Member', new_crew_member_path %>

app/views/crew_members/new.html.erb
<h1>New Crew Member</h1>

<%= render 'form', crew_member: @crew_member %>

<%= link_to 'Back', crew_members_path %>

app/views/crew_members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @crew_member.title %>
</p>

<p>
  <strong>First name:</strong>
  <%= @crew_member.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @crew_member.last_name %>
</p>

<p>
  <strong>Job:</strong>
  <%= @crew_member.job %>
</p>

<%= link_to 'Edit', edit_crew_member_path(@crew_member) %> |
<%= link_to 'Back', crew_members_path %>

app/views/home/index.html.erb
<nav>
  <ul>
    <li><%= link_to 'Creatures', creatures_path %></li>
    <li><%= link_to 'Crew Members', crew_members_path %></li>
    <li><%= link_to 'Log Entries', log_entries_path %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project3Expedition</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'home', root_path %>
    <%= yield %>
  </body>
</html>

app/views/log_entries/_form.html.erb
<%= form_with(model: log_entry, local: true) do |form| %>
  <% if log_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(log_entry.errors.count, "error") %> prohibited this log_entry from being saved:</h2>

      <ul>
      <% log_entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :log_type %>
    <%= form.text_field :log_type %>
  </div>

  <div class="field">
    <%= form.label :day_written %>
    <%= form.number_field :day_written %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :crew_member_id %>
    <%= form.select :crew_member_id, CrewMember.all.ids%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/log_entries/edit.html.erb
<h1>Editing Log Entry</h1>

<%= render 'form', log_entry: @log_entry %>

<%= link_to 'Show', @log_entry %> |
<%= link_to 'Back', log_entries_path %>

app/views/log_entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Log Entries</h1>

<table>
  <thead>
    <tr>
      <th>Log type</th>
      <th>Day written</th>
      <th>Content</th>
      <th>Written by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @log_entries.each do |log_entry| %>
      <tr>
        <td><%= log_entry.log_type %></td>
        <td><%= log_entry.day_written %></td>
        <td><%= log_entry.content %></td>
        <td><%= log_entry.crew_member_id %></td>
        <td><%= link_to 'Show', log_entry %></td>
        <td><%= link_to 'Edit', edit_log_entry_path(log_entry) %></td>
        <td><%= link_to 'Destroy', log_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Log Entry', new_log_entry_path %>

app/views/log_entries/new.html.erb
<h1>New Log Entry</h1>

<%= render 'form', log_entry: @log_entry %>

<%= link_to 'Back', log_entries_path %>

app/views/log_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Log type:</strong>
  <%= @log_entry.log_type %>
</p>

<p>
  <strong>Day written:</strong>
  <%= @log_entry.day_written %>
</p>

<p>
  <strong>Content:</strong>
  <%= @log_entry.content %>
</p>

<p>
  <strong>Written by:</strong>
  <%= @log_entry.crew_member_id %>
</p>

<%= link_to 'Edit', edit_log_entry_path(@log_entry) %> |
<%= link_to 'Back', log_entries_path %>